#!/usr/bin/env bash
export REDIRECT_ROOT=${REDIRECT_ROOT:="/var/lib/dokku/services/redirect"}

export PLUGIN_UNIMPLEMENTED_SUBCOMMANDS=()
export PLUGIN_COMMAND_PREFIX="redirect"
export PLUGIN_CONFIG_ROOT=${PLUGIN_CONFIG_ROOT:="$DOKKU_LIB_ROOT/config/$PLUGIN_COMMAND_PREFIX"}
export PLUGIN_DATA_ROOT=$REDIRECT_ROOT
export PLUGIN_BASE_PATH="$PLUGIN_PATH"
if [[ -n $DOKKU_API_VERSION ]]; then
  export PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi

if [[ -d "$PLUGIN_DATA_ROOT/*" ]]; then
  rm -rf "${PLUGIN_DATA_ROOT:?}/*"
fi
