#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"

redirect-set-cmd() {
  #E add a redirect rule:
  #E dokku $PLUGIN_COMMAND_PREFIX:set my-app ma.dokku.me my-app.dokku.me
  #E you can also specify a redirect code (defaults to 301):
  #E dokku $PLUGIN_COMMAND_PREFIX:set my-app ma.dokku.me my-app.dokku.me 302
  #A app, app to run command against
  #A source, source domain
  #A dest, source domain
  #A code, (optional) redirect code
  declare desc="set a redirect from <src> domain to <dest> domain"
  local cmd="$PLUGIN_COMMAND_PREFIX:set" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1" SOURCE="$2" DEST="$3" CODE="${4:-301}"
  [[ -z "$APP" ]] && echo "Please specify an app to run the command on" && exit 1
  verify_app_name "$APP"

  local APP_ROOT="$DOKKU_ROOT/$APP"
  local REDIRECT_FILE="$APP_ROOT/REDIRECTS"
  [[ -z "$SOURCE" || -z "$DEST" ]] && echo "Please provide a source domain and a destination" && exit 1

  touch "$REDIRECT_FILE"
  grep -q "^$SOURCE:" "$REDIRECT_FILE" && dokku_log_fail "Source domain is already redirected"
  dokku_log_info1 "Setting redirect for $APP..."
  echo "$SOURCE:$DEST:$CODE" >>"$REDIRECT_FILE"
  is_deployed "$APP" && plugn trigger proxy-build-config "$APP"
  dokku_log_verbose "Done"
}

redirect-set-cmd "$@"
