#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"

redirect-unset-cmd() {
  #E remove a redirect rule:
  #E dokku $PLUGIN_COMMAND_PREFIX:unset my-app ma.dokku.me
  #A app, app to run command against
  #A domain, domain redirect to remove
  declare desc="unset a redirect from <source>"
  local cmd="$PLUGIN_COMMAND_PREFIX:unset" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare APP="$1" DOMAIN="$2"
  [[ -z "$APP" ]] && echo "Please specify an app to run the command on" && exit 1
  verify_app_name "$APP"

  local APP_ROOT="$DOKKU_ROOT/$APP"
  local REDIRECT_FILE="$APP_ROOT/REDIRECTS"
  [[ -z "$DOMAIN" ]] && echo "Please provide a source domain" && exit 1

  dokku_log_info1 "Unsetting redirect for $APP..."
  touch "$REDIRECT_FILE"
  sed -i "/^$DOMAIN:.*/d" "$REDIRECT_FILE"
  is_deployed "$APP" && plugn trigger proxy-build-config "$APP"
  dokku_log_verbose "Done"
}

redirect-unset-cmd "$@"
